/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.app.test.Dragonfly;
import org.plateau.instance.factory.SingletonInstanceFactory;

import java.lang.reflect.Field;


public class Main {
    public static void main(String[] args) {
        SingletonInstanceFactory factory = new SingletonInstanceFactory();
        Object fly = factory.getInstance(Dragonfly.class);

        printOneClassInfo(fly.getClass());
    }

    private static void printOneClassInfo(Class<?> cl){

        System.out.println(cl.getSimpleName());
        for (Field field : cl.getFields()){
            System.out.println(field.getName());
        }
    }


}
